// Generates src/app/core/version.ts before every local/CI build & test.
// Local: auto-incremented 0.0.N per run (counter file is gitignored).
// CI (CI=true / GITHUB_ACTIONS): deterministic package.json version + sha.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

const isCI = process.env['CI'] === 'true' || Boolean(process.env['GITHUB_ACTIONS']);

let sha = 'nogit';
try {
  sha = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim() || sha;
} catch {
  // no git available (e.g. shallow CI edge) — keep fallback
}

const d = new Date();

let version;
if (isCI) {
  version = `${pkg.version}+${sha}`;
} else {
  // local auto-increment: v0.0.1, v0.0.2, … (counter is gitignored)
  const counterFile = new URL('./.version-counter', import.meta.url);
  let n = 0;
  try {
    n = Number(readFileSync(counterFile, 'utf8')) || 0;
  } catch {
    // first run — start at 0
  }
  n += 1;
  writeFileSync(counterFile, `${n}\n`);
  version = `0.0.${n}`;
}

writeFileSync(
  new URL('../src/app/core/version.ts', import.meta.url),
  `// Auto-generated by scripts/set-version.mjs (npm pre* hook). Do not edit.\n` +
    `export const APP_VERSION = '${version}';\n` +
    `export const APP_BUILT_AT = '${d.toISOString()}';\n`,
);
console.log(`version: ${version}`);
