// Generates src/app/core/version.ts (idempotent, no side effects).
// Version derives from git: 0.0.<commit-count>+<sha>, so it only ever
// changes when code changes (each deploy), never on local rebuilds,
// restarts, or test runs. Safe to run via npm pre* hooks.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

let sha = 'nogit';
let count = '0';
try {
  sha = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim() || sha;
  count = execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim() || count;
  if (!/^\d+$/.test(count)) count = '0';
} catch {
  // no git available — keep fallbacks
}

const version = `0.0.${count}+${sha}`;

writeFileSync(
  new URL('../src/app/core/version.ts', import.meta.url),
  `// Auto-generated by scripts/set-version.mjs (npm pre* hook). Do not edit.\n` +
    `export const APP_VERSION_SHORT = '0.0.${count}';\n`,
);
console.log(`version: ${version}`);
